services:
  db:
    build: .
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - wow-db:/var/lib/postgresql/data 
    ports:
      - 5432:5432

volumes:
  wow-db:


