services:
  db:
    build: .
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: wow-db
      POSTGRES_INITDB_ARGS: "-c shared_preload_libraries=timescaledb"
    volumes:
      - wow-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    command:
      - "-c"
      - "shared_preload_libraries=supabase_vault"
      - "-c"
      - "vault.getkey_script=/scripts/get_key.sh"
    secrets:
      - vault_encryption_key
      - battlenet_client
      - battlenet_secret
  postgrest:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_URI: postgres://authenticator:mysecretpassword@db:5432/wow-db
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_SCHEMAS: api
    depends_on:
      - db

volumes:
  wow-db:


secrets:
  vault_encryption_key:
    file: vault_encryption.secret
  battlenet_client:
    file: battlenetclient.secret
  battlenet_secret:
    file: battlenetsecret.secret