[flyway]
locations = ["filesystem:migrations", "filesystem:functions"]

[environments.default]
locations = ["filesystem:migrations", "filesystem:functions"]
url = "jdbc:postgresql://127.0.0.1:5432/wow-db"
user = "postgres"
password = "postgres"
