[flyway]
locations = ["filesystem:migrations", "filesystem:functions", "filesystem:tutorial","filesystem:pages"]

[environments.default]
locations = ["filesystem:migrations", "filesystem:functions", "filesystem:tutorial","filesystem:pages"]
schemas = ["public", "api"]
url = "jdbc:postgresql://localhost:5432/wow-db"
user = "postgres"
password = "postgres"
